import { makeStyles } from 'tss-react/mui';
const useStyles = makeStyles<{ isLogin?: boolean }>()((theme, { isLogin }) => ({
  fieldsContainer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  roundTemplate: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: '5%',
    width: `${isLogin ? '25vw' : '65vw'}`,
    height: '75vh',
    backgroundColor: '#ffffff54',
    backdropFilter: 'blur(10px)',
    borderRadius: '10px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)',
  },
  registryStyleForm: {
    height: '100%',
    width: `${isLogin ? '100%' : '45%'}`,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'start',
  },
  loginContainer: {
    marginTop: '25px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    width: '100%',
    height: '50%',
    backgroundColor: '',
  },
  selectLocation: {
    height: '100%',
    width: `${isLogin ? '0%' : '50%'}`,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: `${isLogin ? '0px' : '30px'}`,
  },

  titleContainer: {
    width: '100%',
    height: '20%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  iconHomeContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    height: '80%',
  },
  titleNameContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    height: '10%',
  },
  title: {
    marginTop: '-12px',
    fontSize: '1.7rem',
    textShadow: '1px 1px 1px black',
    color: theme.palette.common.spoofy,
  },

  containerField: {
    margin: '10px',
    width: '85%',
    height: '80%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
  },
  containerSubmit: {
    width: '50%',
    height: '10%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  toggleButton: {
    width: '30%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  divForCenterIcon: { width: '30%', height: '100%' },
  btn: {
    transition: '0.6s',
    borderRadius: '20px',
    backgroundSize: '200%',
    width: '120px',
    backgroundImage: theme.palette.background.buttonColors.submit,
    '&:hover': {
      backgroundPosition: 'right',
    },
  },

  btnToggle: {
    transition: '0.6s',
    borderRadius: '12px',
    backgroundSize: '200%',
    width: '100px',
    height: '32px',
    color: 'black',
    backgroundImage: theme.palette.background.buttonColors.submit,
    '&:hover': {
      backgroundPosition: 'right',
    },
  },
}));

export default useStyles;
